base-ubuntu-nvm-node-npm:
  variables:
    CONTAINER_IMAGE: boldt/base-ubuntu-nvm-node-npm
  script:
  - docker build -t $CONTAINER_IMAGE:latest ./base-ubuntu-nvm-node-npm
  - docker push $CI_REGISTRY/$CONTAINER_IMAGE:latest

#######################################################################

docker-express-example:
  variables:
    CONTAINER_IMAGE: boldt/docker-express-example
  script:
  - docker build -t $CONTAINER_IMAGE:latest ./docker-express-example
  - docker push $CI_REGISTRY/$CONTAINER_IMAGE:latest

#######################################################################

node-ws-server:
  variables:
    CONTAINER_IMAGE: boldt/node-ws-server
  script:
  - docker build -t $CONTAINER_IMAGE:latest ./node-ws-server
  - docker push $CI_REGISTRY/$CONTAINER_IMAGE:latest

#######################################################################

ubuntu-apache2-mod_md:
  variables:
    CONTAINER_IMAGE: boldt/ubuntu-apache2-mod_md
  script:
  - docker build -t $CONTAINER_IMAGE:latest ./ubuntu-apache2-mod_md
  - docker push $CI_REGISTRY/$CONTAINER_IMAGE:latest

