base-ubuntu-nvm-node-npm:
  variables:
    CONTAINER_IMAGE: boldt/base-ubuntu-nvm-node-npm
    FOLDER: ./base-ubuntu-nvm-node-npm
  script:
  - docker build -t $CI_REGISTRY/$CONTAINER_IMAGE:latest --build-arg CACHEBUST=$(date +%s) $FOLDER
  - docker push $CI_REGISTRY/$CONTAINER_IMAGE:latest
  - docker rmi $CI_REGISTRY/$CONTAINER_IMAGE:latest

#######################################################################

docker-express-example:
  variables:
    CONTAINER_IMAGE: boldt/docker-express-example
    FOLDER: ./docker-express-example
  script:
  - docker build -t $CI_REGISTRY/$CONTAINER_IMAGE:latest --build-arg CACHEBUST=$(date +%s) $FOLDER
  - docker push $CI_REGISTRY/$CONTAINER_IMAGE:latest
  - docker rmi $CI_REGISTRY/$CONTAINER_IMAGE:latest

#######################################################################

node-ws-server:
  variables:
    CONTAINER_IMAGE: boldt/node-ws-server
    FOLDER: ./node-ws-server
  script:
  - docker build -t $CI_REGISTRY/$CONTAINER_IMAGE:latest --build-arg CACHEBUST=$(date +%s) $FOLDER
  - docker push $CI_REGISTRY/$CONTAINER_IMAGE:latest
  - docker rmi $CI_REGISTRY/$CONTAINER_IMAGE:latest

#######################################################################

#ubuntu-apache2-mod-md:
#  variables:
#    CONTAINER_IMAGE: boldt/ubuntu-apache2-mod_md
#    FOLDER: ./ubuntu-apache2-mod_md
#  script:
#  - docker build -t $CI_REGISTRY/$CONTAINER_IMAGE:latest --build-arg CACHEBUST=$(date +%s) $FOLDER
#  - docker push $CI_REGISTRY/$CONTAINER_IMAGE:latest
#  - docker rmi $CI_REGISTRY/$CONTAINER_IMAGE:latest

